spring:
  application:
    name: project02
  datasource:
    # 사용할 드라이브 이름: 여기서 mariadb를 사용
    driver-class-name: org.mariadb.jdbc.Driver
    # 사용할 db의 user name
    username: smart01
    # 사용할 db의 user password
    password: smart01
    # 사용할 db의 url 주소
    url: jdbc:mariadb://localhost:3306/smart01db
    # devtools 세팅 여기서 사용가능으로 세팅
  devtools:
    livereload:
      enabled: true
      # 다시 시작을 가능하게 만듬
    restart:
      enabled: false

# mvc가 스캔할 풀더를 지정하고, 해당 풀더의 확장자도 지정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# servlet 설정
server:
  servlet:
    jsp:
      init-parameters:
        developments: true

# JSP trim spaces
        trimSpaces: true
# encoding for servlet and html
    encoding:
      force: true
# MyBatis
# mapper할 경로
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml


# (1) cacheEnabled ===> default: true
# All xml for mapper cache defined no limit
# (2) jdbcTypeForNull ===> database field에 null 값을 넣을 때 사용한다.
# ===> 부적절한 column의 유령 xxxx 오류가 발생한다.
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
    
